#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_IBM_ASM)		+= ibmasm/
obj-$(CONFIG_HDPU_FEATURES)	+= hdpuftrs/
obj-$(CONFIG_ATMEL_PWM)		+= atmel_pwm.o
obj-$(CONFIG_ATMEL_SSC)		+= atmel-ssc.o
obj-$(CONFIG_ATMEL_TCLIB)	+= atmel_tclib.o
obj-$(CONFIG_ICS932S401)	+= ics932s401.o
obj-$(CONFIG_LKDTM)		+= lkdtm.o
obj-$(CONFIG_TIFM_CORE)       	+= tifm_core.o
obj-$(CONFIG_TIFM_7XX1)       	+= tifm_7xx1.o
obj-$(CONFIG_PHANTOM)		+= phantom.o
obj-$(CONFIG_ANDROID_PMEM)	+= pmem.o
obj-$(CONFIG_ANDROID_PMEM_KAPI_TEST)	+= pmem_kernel_test.o
obj-$(CONFIG_SGI_IOC4)		+= ioc4.o
obj-$(CONFIG_ENCLOSURE_SERVICES) += enclosure.o
obj-$(CONFIG_KERNEL_DEBUGGER_CORE)	+= kernel_debugger.o
obj-$(CONFIG_KGDB_TESTS)	+= kgdbts.o
obj-$(CONFIG_SGI_XP)		+= sgi-xp/
obj-$(CONFIG_SGI_GRU)		+= sgi-gru/
obj-$(CONFIG_HP_ILO)		+= hpilo.o
obj-$(CONFIG_UID_STAT)		+= uid_stat.o
obj-$(CONFIG_IFACE_STAT)	+= iface_stat.o
obj-$(CONFIG_C2PORT)		+= c2port/
obj-$(CONFIG_MSM_PMIC_LIGHTSENSOR)	+= msm-pmic-lightsensor.o
obj-$(CONFIG_SEMCCLASS)		+= semc/
obj-$(CONFIG_SEMC_SEPORT)	+= semc/seport/
obj-$(CONFIG_SEMC_MSM_PMIC_VIBRATOR)	+= semc/vibrator/
obj-$(CONFIG_MSM_SIM_CARD_DETECT)	+= semc/simcdetect/
obj-$(CONFIG_SENSORS_ES209RA_PROXIMITY)	+= es209ra_proximity.o
obj-$(CONFIG_ES209RA_WLAN_POWER)	+= es209ra_wlan_power.o
obj-$(CONFIG_SEMC_POWER)	+= semc/power/
obj-y				+= eeprom/
obj-$(CONFIG_MSM_720P_CORE)	+= video_core/720p/
obj-$(CONFIG_TSIF) += msm_tsif.o
msm_tsif-objs := tsif.o

obj-$(CONFIG_TSIF_CHRDEV) += tsif_chrdev.o
obj-$(CONFIG_PMIC8058_PWM) += pmic8058-pwm.o
obj-$(CONFIG_CRASH_DUMP) += 	msm_amss_coredump.o
obj-y				+= semc/gpio_matrix/

